parameters = [ "lxir131.gsi.de", "/lustre/astrum/experiment_data/2024-05_E018/OnlineDataAnalysisSystem/queqiao", "activate iqt7_env_ruijiu", "/u/litv-exp/mambaforge/bin/queqiao", "../parameters/queqiaosettings_E143Exp_simulation.toml",]
